
const products= [
    {
       id:"1",
        title: "Abaya",
        like: true,
        img: require("../../src/Images/abaya.png"),
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo accusantium, quos culpa enim quibusdam impedit provident modi ",
        price: 10000,
        countInStock:10,
        rating:4,
        numReviews:4,
    },
    {
        id:"2",
        title: "Abaya",
        like: false,
         img: require("../../src/Images/abaya.png"),
         desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo accusantium, quos culpa enim quibusdam impedit provident modi ",
         price: 10000,
         countInStock:10,
         rating:4,
         numReviews:4,
     },
     { 
        id:"3",
         title: "Abaya",
         like: true,
         img: require("../../src/Images/abaya.png"),
         desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo accusantium, quos culpa enim quibusdam impedit provident modi ",
         price: 10000,
         countInStock:10,
         rating:4,
         numReviews:4,
     },
     {
        id:"4",
         title: "Abaya",
         like: false,
         img: require("../../src/Images/abaya.png"),
         desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo accusantium, quos culpa enim quibusdam impedit provident modi ",
         price: 10000,
         countInStock: 10,
         rating:4,
         numReviews:4,
     },
     {
        id:"5",
         title: "Abaya",
         like: true,
         img: require("../../src/Images/abaya.png"),
         desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo accusantium, quos culpa enim quibusdam impedit provident modi ",
         price: 10000,
         countInStock:10,
         rating:4,
         numReviews:4,
     },
     {
        id:"6",
         title: "Abaya",
         like: true,
         img: require("../../src/Images/abaya.png"),
         desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo accusantium, quos culpa enim quibusdam impedit provident modi ",
         price: 10000,
         countInStock:10,
         rating:4,
         numReviews:4,
     },
     {
        id:"7",
         title: "Abaya",
         like: false,
         img: require("../../src/Images/abaya.png"),
         desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo accusantium, quos culpa enim quibusdam impedit provident modi ",
         price: 10000,
         countInStock:10,
         rating:4,
         numReviews:4,
     },
     {
        id:"8",
         title: "Abaya",
         like: true,
         img: require("../../src/Images/abaya.png"),
         desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo accusantium, quos culpa enim quibusdam impedit provident modi ",
         price: 10000,
         countInStock:10,
         rating:4,
         numReviews:4,
     },
 ]; 

 
export default products;